// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FetchedModel 从上游接口实时拉取的模型信息（统一结构）
 */
export class FetchedModel {
    /**
     * 实际调用用的 model id
     */
    "ID": string;

    /**
     * 显示名
     */
    "Label": string;

    /**
     * 上下文窗口（token）
     */
    "Context": number;

    /**
     * 最大输出（token）
     */
    "Output": number;

    /**
     * 是否支持流式
     */
    "Stream": boolean;

    /**
     * 是否支持视觉
     */
    "Vision": boolean;

    /**
     * 是否支持工具调用
     */
    "ToolCall": boolean;

    /**
     * 是否推理模型
     */
    "Reasoning": boolean;

    /** Creates a new FetchedModel instance. */
    constructor($$source: Partial<FetchedModel> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("Context" in $$source)) {
            this["Context"] = 0;
        }
        if (!("Output" in $$source)) {
            this["Output"] = 0;
        }
        if (!("Stream" in $$source)) {
            this["Stream"] = false;
        }
        if (!("Vision" in $$source)) {
            this["Vision"] = false;
        }
        if (!("ToolCall" in $$source)) {
            this["ToolCall"] = false;
        }
        if (!("Reasoning" in $$source)) {
            this["Reasoning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FetchedModel instance from a string or object.
     */
    static createFrom($$source: any = {}): FetchedModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FetchedModel($$parsedSource as Partial<FetchedModel>);
    }
}
