// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateInfo 更新信息
 */
export class UpdateInfo {
    /**
     * 新版本号（如 "0.1.0"）
     */
    "version": string;

    /**
     * 更新说明（changelog）
     */
    "notes": string;

    /**
     * 资产下载地址
     */
    "assetUrl": string;

    /**
     * 资产文件名
     */
    "assetName": string;

    /**
     * 资产大小（字节）
     */
    "assetSize": number;

    /**
     * 是否强制更新（minor 版本变化为强制，patch 变化为普通）
     */
    "critical": boolean;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("assetUrl" in $$source)) {
            this["assetUrl"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }
        if (!("critical" in $$source)) {
            this["critical"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
