// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ModelSpeed 单个模型的输出速率
 */
export class ModelSpeed {
    "model": string;
    "tps": number;
    "reqs": number;
    "output": number;
    "duration": number;

    /** Creates a new ModelSpeed instance. */
    constructor($$source: Partial<ModelSpeed> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("tps" in $$source)) {
            this["tps"] = 0;
        }
        if (!("reqs" in $$source)) {
            this["reqs"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelSpeed instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelSpeed {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelSpeed($$parsedSource as Partial<ModelSpeed>);
    }
}

/**
 * SourceInfo sources 表的一行（用于前端 UA 辅助配置）
 */
export class SourceInfo {
    "id": number;
    "name": string;
    "userAgent": string;
    "count": number;

    /** Creates a new SourceInfo instance. */
    constructor($$source: Partial<SourceInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceInfo($$parsedSource as Partial<SourceInfo>);
    }
}

/**
 * SourceModelStat 某个 source 历史请求过的模型及次数
 */
export class SourceModelStat {
    "model": string;
    "count": number;
    "lastSeen": string;

    /** Creates a new SourceModelStat instance. */
    constructor($$source: Partial<SourceModelStat> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceModelStat instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceModelStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceModelStat($$parsedSource as Partial<SourceModelStat>);
    }
}

/**
 * SpeedStats 今日输出速率统计
 */
export class SpeedStats {
    "overallTps": number;
    "totalReqs": number;
    "totalOutput": number;
    "totalDuration": number;
    "byModel": ModelSpeed[];

    /** Creates a new SpeedStats instance. */
    constructor($$source: Partial<SpeedStats> = {}) {
        if (!("overallTps" in $$source)) {
            this["overallTps"] = 0;
        }
        if (!("totalReqs" in $$source)) {
            this["totalReqs"] = 0;
        }
        if (!("totalOutput" in $$source)) {
            this["totalOutput"] = 0;
        }
        if (!("totalDuration" in $$source)) {
            this["totalDuration"] = 0;
        }
        if (!("byModel" in $$source)) {
            this["byModel"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpeedStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SpeedStats {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("byModel" in $$parsedSource) {
            $$parsedSource["byModel"] = $$createField4_0($$parsedSource["byModel"]);
        }
        return new SpeedStats($$parsedSource as Partial<SpeedStats>);
    }
}

/**
 * TrendPoint 趋势图一个数据点
 */
export class TrendPoint {
    "label": string;
    "tokens": number;
    "inputTokens": number;
    "outputTokens": number;
    "reqs": number;
    "cacheHitTokens": number;
    "cacheHitReqs": number;

    /** Creates a new TrendPoint instance. */
    constructor($$source: Partial<TrendPoint> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("tokens" in $$source)) {
            this["tokens"] = 0;
        }
        if (!("inputTokens" in $$source)) {
            this["inputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            this["outputTokens"] = 0;
        }
        if (!("reqs" in $$source)) {
            this["reqs"] = 0;
        }
        if (!("cacheHitTokens" in $$source)) {
            this["cacheHitTokens"] = 0;
        }
        if (!("cacheHitReqs" in $$source)) {
            this["cacheHitReqs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrendPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): TrendPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrendPoint($$parsedSource as Partial<TrendPoint>);
    }
}

/**
 * UsageTrend 使用趋势结果
 */
export class UsageTrend {
    "startDate": string;
    "endDate": string;
    "granularity": string;
    "points": TrendPoint[];

    /** Creates a new UsageTrend instance. */
    constructor($$source: Partial<UsageTrend> = {}) {
        if (!("startDate" in $$source)) {
            this["startDate"] = "";
        }
        if (!("endDate" in $$source)) {
            this["endDate"] = "";
        }
        if (!("granularity" in $$source)) {
            this["granularity"] = "";
        }
        if (!("points" in $$source)) {
            this["points"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageTrend instance from a string or object.
     */
    static createFrom($$source: any = {}): UsageTrend {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField3_0($$parsedSource["points"]);
        }
        return new UsageTrend($$parsedSource as Partial<UsageTrend>);
    }
}

// Private type creation functions
const $$createType0 = ModelSpeed.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TrendPoint.createFrom;
const $$createType3 = $Create.Array($$createType2);
