// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BonusProvider 注册送 token 的供应商信息
 */
export class BonusProvider {
    "id": string;
    "name": string;
    "baseUrl": string;
    "registerUrl": string;
    "bonusRule": string;

    /** Creates a new BonusProvider instance. */
    constructor($$source: Partial<BonusProvider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("registerUrl" in $$source)) {
            this["registerUrl"] = "";
        }
        if (!("bonusRule" in $$source)) {
            this["bonusRule"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BonusProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): BonusProvider {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BonusProvider($$parsedSource as Partial<BonusProvider>);
    }
}

/**
 * Catalog 目录根结构
 */
export class Catalog {
    "providers": CatalogProvider[];
    "deprecated": {"id": string, "name": string, "reason": string, "status": string}[];

    /** Creates a new Catalog instance. */
    constructor($$source: Partial<Catalog> = {}) {
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("deprecated" in $$source)) {
            this["deprecated"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Catalog instance from a string or object.
     */
    static createFrom($$source: any = {}): Catalog {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField0_0($$parsedSource["providers"]);
        }
        if ("deprecated" in $$parsedSource) {
            $$parsedSource["deprecated"] = $$createField1_0($$parsedSource["deprecated"]);
        }
        return new Catalog($$parsedSource as Partial<Catalog>);
    }
}

/**
 * CatalogModel 目录中的单个免费模型
 */
export class CatalogModel {
    "id": string;
    "name": string;

    /**
     * "1M"、"131K"、"32K" 文本
     */
    "context": string;

    /**
     * 免费方式/限流描述
     */
    "rate_limit": string;

    /**
     * 能力标记（来自上游目录，用于前端展示/过滤）
     * 思维链/推理模型
     */
    "reasoning"?: boolean;

    /**
     * 支持函数/工具调用
     */
    "tool_call"?: boolean;

    /**
     * 支持图片/多模态输入
     */
    "vision"?: boolean;

    /**
     * 支持结构化输出（JSON schema）
     */
    "structured_output"?: boolean;

    /** Creates a new CatalogModel instance. */
    constructor($$source: Partial<CatalogModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }
        if (!("rate_limit" in $$source)) {
            this["rate_limit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogModel instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogModel($$parsedSource as Partial<CatalogModel>);
    }
}

/**
 * CatalogProvider 目录中的供应商（来自 provider_apis_catalog.json）
 */
export class CatalogProvider {
    "id": string;
    "name": string;

    /**
     * "international" | "domestic"
     */
    "region": string;
    "base_url": string;
    "get_api_key_url": string;
    "auth_method": string;
    "credit_card_required": boolean;
    "openai_compatible": boolean;

    /**
     * 出站协议：openai（默认）| anthropic；空值按 OpenAICompatible 推断
     */
    "protocol"?: string;

    /**
     * "1M"、"131K" 等文本
     */
    "max_context": string;
    "free_models_count": number;
    "free_models": CatalogModel[];

    /** Creates a new CatalogProvider instance. */
    constructor($$source: Partial<CatalogProvider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("get_api_key_url" in $$source)) {
            this["get_api_key_url"] = "";
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = "";
        }
        if (!("credit_card_required" in $$source)) {
            this["credit_card_required"] = false;
        }
        if (!("openai_compatible" in $$source)) {
            this["openai_compatible"] = false;
        }
        if (!("max_context" in $$source)) {
            this["max_context"] = "";
        }
        if (!("free_models_count" in $$source)) {
            this["free_models_count"] = 0;
        }
        if (!("free_models" in $$source)) {
            this["free_models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): CatalogProvider {
        const $$createField11_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("free_models" in $$parsedSource) {
            $$parsedSource["free_models"] = $$createField11_0($$parsedSource["free_models"]);
        }
        return new CatalogProvider($$parsedSource as Partial<CatalogProvider>);
    }
}

/**
 * ImportItem 一条导入指令（前端预览/解决冲突后下发）
 */
export class ImportItem {
    "provider": ShareProvider;
    "strategy": ImportStrategy;

    /**
     * rename 时使用；为空则自动加 -2/-3…
     */
    "newId": string;

    /** Creates a new ImportItem instance. */
    constructor($$source: Partial<ImportItem> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = (new ShareProvider());
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = ImportStrategy.$zero;
        }
        if (!("newId" in $$source)) {
            this["newId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportItem {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField0_0($$parsedSource["provider"]);
        }
        return new ImportItem($$parsedSource as Partial<ImportItem>);
    }
}

/**
 * ImportStrategy 单个供应商的导入冲突处理
 */
export enum ImportStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 覆盖已存在的同 id 供应商
     */
    ImportOverwrite = "overwrite",

    /**
     * 跳过（不导入）
     */
    ImportSkip = "skip",

    /**
     * 以新 id 导入（保留双方）
     */
    ImportRename = "rename",
};

/**
 * LocksetInfo 对外暴露的锁状态信息
 */
export class LocksetInfo {
    /**
     * 是否已初始化加密（kdf 存在，含自动加密）
     */
    "isSet": boolean;

    /**
     * 用户是否主动设置了主密码（false=自动加密）
     */
    "masterSet": boolean;

    /**
     * 是否已生成恢复码
     */
    "hasRecovery": boolean;

    /**
     * 当前是否锁定
     */
    "isLocked": boolean;

    /**
     * 主密码是否已在本机记住（钥匙串）
     */
    "remembered": boolean;

    /** Creates a new LocksetInfo instance. */
    constructor($$source: Partial<LocksetInfo> = {}) {
        if (!("isSet" in $$source)) {
            this["isSet"] = false;
        }
        if (!("masterSet" in $$source)) {
            this["masterSet"] = false;
        }
        if (!("hasRecovery" in $$source)) {
            this["hasRecovery"] = false;
        }
        if (!("isLocked" in $$source)) {
            this["isLocked"] = false;
        }
        if (!("remembered" in $$source)) {
            this["remembered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocksetInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LocksetInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocksetInfo($$parsedSource as Partial<LocksetInfo>);
    }
}

export class ProviderConfig {
    /**
     * 唯一 id：目录 slug 或 custom-<随机>
     */
    "id": string;

    /**
     * 显示名
     */
    "name": string;

    /**
     * OpenAI 兼容地址
     */
    "baseURL": string;

    /**
     * 密钥（内存明文；落盘时由 Manager 加密）
     */
    "apiKey": string;

    /**
     * 申请 key 地址
     */
    "getAPIKeyURL": string;

    /**
     * 出站协议：openai（默认）| anthropic
     */
    "protocol": string;

    /**
     * 最大上下文（可选）
     */
    "maxContext": number;

    /**
     * 是否手动自定义添加
     */
    "custom": boolean;

    /**
     * 是否通过分享文件导入
     */
    "imported": boolean;

    /**
     * provider 是否至少评测通过一个模型
     */
    "verified": boolean;

    /**
     * 该 provider 的模型（逐个评测通过才加）
     */
    "models": ProviderModel[];

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("getAPIKeyURL" in $$source)) {
            this["getAPIKeyURL"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("maxContext" in $$source)) {
            this["maxContext"] = 0;
        }
        if (!("custom" in $$source)) {
            this["custom"] = false;
        }
        if (!("imported" in $$source)) {
            this["imported"] = false;
        }
        if (!("verified" in $$source)) {
            this["verified"] = false;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        const $$createField10_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField10_0($$parsedSource["models"]);
        }
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

/**
 * ProviderModel 单个免费模型（模型级 verified/healthy 状态，支持逐个评测 + 健康监控）
 */
export class ProviderModel {
    /**
     * 原始 model id（如 "llama-3.3-70b"）
     */
    "id": string;

    /**
     * 上下文窗口
     */
    "context": number;

    /**
     * 是否评测通过（未通过不参与路由）
     */
    "verified": boolean;

    /**
     * 后台监控状态（每 5 分钟探测；false=权重降级）
     */
    "healthy": boolean;

    /**
     * 连续失败次数（监控用）
     */
    "failCount": number;

    /**
     * 最近一次评测的输出速度（tok/s）
     */
    "tps": number;

    /** Creates a new ProviderModel instance. */
    constructor($$source: Partial<ProviderModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = 0;
        }
        if (!("verified" in $$source)) {
            this["verified"] = false;
        }
        if (!("healthy" in $$source)) {
            this["healthy"] = false;
        }
        if (!("failCount" in $$source)) {
            this["failCount"] = 0;
        }
        if (!("tps" in $$source)) {
            this["tps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderModel instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderModel($$parsedSource as Partial<ProviderModel>);
    }
}

/**
 * SharePreview 不解密时能看到的元信息（加密文件看不到供应商）
 */
export class SharePreview {
    "version": number;
    "encrypted": boolean;

    /**
     * kdf=argon2id 需要密码；kdf=embedded 无需密码
     */
    "needPasswd": boolean;

    /** Creates a new SharePreview instance. */
    constructor($$source: Partial<SharePreview> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("encrypted" in $$source)) {
            this["encrypted"] = false;
        }
        if (!("needPasswd" in $$source)) {
            this["needPasswd"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): SharePreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SharePreview($$parsedSource as Partial<SharePreview>);
    }
}

/**
 * ShareProvider 分享的单个供应商（只含可分享字段，不含本地运行时状态）
 */
export class ShareProvider {
    "id": string;
    "name": string;
    "baseURL": string;
    "getAPIKeyURL": string;
    "protocol": string;
    "custom": boolean;
    "apiKey": string;
    "models": ProviderModel[];

    /** Creates a new ShareProvider instance. */
    constructor($$source: Partial<ShareProvider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("getAPIKeyURL" in $$source)) {
            this["getAPIKeyURL"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("custom" in $$source)) {
            this["custom"] = false;
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareProvider {
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField7_0($$parsedSource["models"]);
        }
        return new ShareProvider($$parsedSource as Partial<ShareProvider>);
    }
}

// Private type creation functions
const $$createType0 = CatalogProvider.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CatalogModel.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ShareProvider.createFrom;
const $$createType6 = ProviderModel.createFrom;
const $$createType7 = $Create.Array($$createType6);
