// Code generated from pricing.json. DO NOT EDIT manually.

package pricing

// DefaultRates 内置默认费率（每百万 token 成本，美元）
// 本地无费率文件时，从这些硬编码还原。
// 如需更新默认费率，重新生成本文件或编辑后保存到配置文件。

var DefaultRates = []Price{
	{ModelID: "claude-3-5-haiku-20241022", DisplayName: "Claude 3.5 Haiku", InputPerMillion: 0.8, OutputPerMillion: 4, CacheRead: 0.08, CacheCreation: 1},
	{ModelID: "claude-3-5-sonnet-20241022", DisplayName: "Claude 3.5 Sonnet", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 3.75},
	{ModelID: "claude-fable-5", DisplayName: "Claude Fable 5", InputPerMillion: 10, OutputPerMillion: 50, CacheRead: 1, CacheCreation: 12.5},
	{ModelID: "claude-haiku-4-5-20251001", DisplayName: "Claude Haiku 4.5", InputPerMillion: 1, OutputPerMillion: 5, CacheRead: 0.1, CacheCreation: 1.25},
	{ModelID: "claude-mythos-5", DisplayName: "Claude Mythos 5", InputPerMillion: 10, OutputPerMillion: 50, CacheRead: 1, CacheCreation: 12.5},
	{ModelID: "claude-opus-4-1-20250805", DisplayName: "Claude Opus 4.1", InputPerMillion: 15, OutputPerMillion: 75, CacheRead: 1.5, CacheCreation: 18.75},
	{ModelID: "claude-opus-4-20250514", DisplayName: "Claude Opus 4", InputPerMillion: 15, OutputPerMillion: 75, CacheRead: 1.5, CacheCreation: 18.75},
	{ModelID: "claude-opus-4-5-20251101", DisplayName: "Claude Opus 4.5", InputPerMillion: 5, OutputPerMillion: 25, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "claude-opus-4-6", DisplayName: "Claude Opus 4.6", InputPerMillion: 5, OutputPerMillion: 25, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "claude-opus-4-6-20260206", DisplayName: "Claude Opus 4.6", InputPerMillion: 5, OutputPerMillion: 25, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "claude-opus-4-7", DisplayName: "Claude Opus 4.7", InputPerMillion: 5, OutputPerMillion: 25, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "claude-opus-4-8", DisplayName: "Claude Opus 4.8", InputPerMillion: 5, OutputPerMillion: 25, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "claude-opus-5", DisplayName: "Claude Opus 5", InputPerMillion: 5, OutputPerMillion: 25, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "claude-sonnet-4-20250514", DisplayName: "Claude Sonnet 4", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 3.75},
	{ModelID: "claude-sonnet-4-5-20250929", DisplayName: "Claude Sonnet 4.5", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 3.75},
	{ModelID: "claude-sonnet-4-6", DisplayName: "Claude Sonnet 4.6", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 3.75},
	{ModelID: "claude-sonnet-4-6-20260217", DisplayName: "Claude Sonnet 4.6", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 3.75},
	{ModelID: "claude-sonnet-5", DisplayName: "Claude Sonnet 5", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 3.75},
	{ModelID: "codestral-2508", DisplayName: "Codestral", InputPerMillion: 0.3, OutputPerMillion: 0.9, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "codex-mini", DisplayName: "Codex Mini", InputPerMillion: 0.75, OutputPerMillion: 3, CacheRead: 0.025, CacheCreation: 0},
	{ModelID: "command-a", DisplayName: "Cohere Command A", InputPerMillion: 2.5, OutputPerMillion: 10, CacheRead: 0, CacheCreation: 0},
	{ModelID: "command-r", DisplayName: "Cohere Command R", InputPerMillion: 0.15, OutputPerMillion: 0.6, CacheRead: 0, CacheCreation: 0},
	{ModelID: "command-r-plus", DisplayName: "Cohere Command R+", InputPerMillion: 2.5, OutputPerMillion: 10, CacheRead: 0, CacheCreation: 0},
	{ModelID: "deepseek-chat", DisplayName: "DeepSeek Chat", InputPerMillion: 0.14, OutputPerMillion: 0.28, CacheRead: 0.0028, CacheCreation: 0},
	{ModelID: "deepseek-reasoner", DisplayName: "DeepSeek Reasoner", InputPerMillion: 0.14, OutputPerMillion: 0.28, CacheRead: 0.0028, CacheCreation: 0},
	{ModelID: "deepseek-v3", DisplayName: "DeepSeek V3", InputPerMillion: 0.28, OutputPerMillion: 1.11, CacheRead: 0.028, CacheCreation: 0},
	{ModelID: "deepseek-v3.1", DisplayName: "DeepSeek V3.1", InputPerMillion: 0.55, OutputPerMillion: 1.67, CacheRead: 0.055, CacheCreation: 0},
	{ModelID: "deepseek-v3.2", DisplayName: "DeepSeek V3.2", InputPerMillion: 0.28, OutputPerMillion: 0.42, CacheRead: 0.028, CacheCreation: 0},
	{ModelID: "deepseek-v4-flash", DisplayName: "DeepSeek V4 Flash", InputPerMillion: 0.14, OutputPerMillion: 0.28, CacheRead: 0.0028, CacheCreation: 0},
	{ModelID: "deepseek-v4-pro", DisplayName: "DeepSeek V4 Pro", InputPerMillion: 0.435, OutputPerMillion: 0.87, CacheRead: 0.003625, CacheCreation: 0},
	{ModelID: "devstral-2-2512", DisplayName: "Devstral 2", InputPerMillion: 0.4, OutputPerMillion: 2, CacheRead: 0.04, CacheCreation: 0},
	{ModelID: "devstral-medium", DisplayName: "Devstral Medium", InputPerMillion: 0.4, OutputPerMillion: 2, CacheRead: 0.04, CacheCreation: 0},
	{ModelID: "devstral-small-1.1", DisplayName: "Devstral Small 1.1", InputPerMillion: 0.07, OutputPerMillion: 0.28, CacheRead: 0.01, CacheCreation: 0},
	{ModelID: "devstral-small-2-2512", DisplayName: "Devstral Small 2", InputPerMillion: 0.1, OutputPerMillion: 0.3, CacheRead: 0.01, CacheCreation: 0},
	{ModelID: "doubao-seed-2-0-code", DisplayName: "Doubao Seed 2.0 Code", InputPerMillion: 0.47, OutputPerMillion: 2.37, CacheRead: 0.09, CacheCreation: 0},
	{ModelID: "doubao-seed-2-0-code-preview-latest", DisplayName: "Doubao Seed 2.0 Code Preview", InputPerMillion: 0.47, OutputPerMillion: 2.37, CacheRead: 0.09, CacheCreation: 0},
	{ModelID: "doubao-seed-2-0-lite", DisplayName: "Doubao Seed 2.0 Lite", InputPerMillion: 0.08, OutputPerMillion: 0.5, CacheRead: 0.017, CacheCreation: 0},
	{ModelID: "doubao-seed-2-0-mini", DisplayName: "Doubao Seed 2.0 Mini", InputPerMillion: 0.03, OutputPerMillion: 0.31, CacheRead: 0.0056, CacheCreation: 0},
	{ModelID: "doubao-seed-2-0-pro", DisplayName: "Doubao Seed 2.0 Pro", InputPerMillion: 0.47, OutputPerMillion: 2.37, CacheRead: 0.09, CacheCreation: 0},
	{ModelID: "doubao-seed-2-1-pro", DisplayName: "Doubao Seed 2.1 Pro", InputPerMillion: 0.84, OutputPerMillion: 4.2, CacheRead: 0.17, CacheCreation: 0},
	{ModelID: "doubao-seed-2-1-turbo", DisplayName: "Doubao Seed 2.1 Turbo", InputPerMillion: 0.42, OutputPerMillion: 2.1, CacheRead: 0.08, CacheCreation: 0},
	{ModelID: "doubao-seed-code", DisplayName: "Doubao Seed Code", InputPerMillion: 0.17, OutputPerMillion: 1.11, CacheRead: 0.02, CacheCreation: 0},
	{ModelID: "gemini-2.0-flash", DisplayName: "Gemini 2.0 Flash", InputPerMillion: 0.1, OutputPerMillion: 0.4, CacheRead: 0.025, CacheCreation: 0},
	{ModelID: "gemini-2.5-flash", DisplayName: "Gemini 2.5 Flash", InputPerMillion: 0.3, OutputPerMillion: 2.5, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "gemini-2.5-flash-lite", DisplayName: "Gemini 2.5 Flash Lite", InputPerMillion: 0.1, OutputPerMillion: 0.4, CacheRead: 0.01, CacheCreation: 0},
	{ModelID: "gemini-2.5-pro", DisplayName: "Gemini 2.5 Pro", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gemini-3-flash-preview", DisplayName: "Gemini 3 Flash Preview", InputPerMillion: 0.5, OutputPerMillion: 3, CacheRead: 0.05, CacheCreation: 0},
	{ModelID: "gemini-3-pro-preview", DisplayName: "Gemini 3 Pro Preview", InputPerMillion: 2, OutputPerMillion: 12, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "gemini-3.1-flash-lite", DisplayName: "Gemini 3.1 Flash Lite", InputPerMillion: 0.25, OutputPerMillion: 1.5, CacheRead: 0.025, CacheCreation: 0},
	{ModelID: "gemini-3.1-flash-lite-preview", DisplayName: "Gemini 3.1 Flash Lite Preview", InputPerMillion: 0.25, OutputPerMillion: 1.5, CacheRead: 0.025, CacheCreation: 0},
	{ModelID: "gemini-3.1-pro-preview", DisplayName: "Gemini 3.1 Pro Preview", InputPerMillion: 2, OutputPerMillion: 12, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "gemini-3.5-flash", DisplayName: "Gemini 3.5 Flash", InputPerMillion: 1.5, OutputPerMillion: 9, CacheRead: 0.15, CacheCreation: 0},
	{ModelID: "gemini-3.5-flash-lite", DisplayName: "Gemini 3.5 Flash Lite", InputPerMillion: 0.3, OutputPerMillion: 2.5, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "gemini-3.6-flash", DisplayName: "Gemini 3.6 Flash", InputPerMillion: 1.5, OutputPerMillion: 7.5, CacheRead: 0.15, CacheCreation: 0},
	{ModelID: "glm-4.6", DisplayName: "GLM-4.6", InputPerMillion: 0.6, OutputPerMillion: 2.2, CacheRead: 0.11, CacheCreation: 0},
	{ModelID: "glm-4.7", DisplayName: "GLM-4.7", InputPerMillion: 0.6, OutputPerMillion: 2.2, CacheRead: 0.11, CacheCreation: 0},
	{ModelID: "glm-5", DisplayName: "GLM-5", InputPerMillion: 1, OutputPerMillion: 3.2, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "glm-5-turbo", DisplayName: "GLM-5-Turbo", InputPerMillion: 1.2, OutputPerMillion: 4, CacheRead: 0.24, CacheCreation: 0},
	{ModelID: "glm-5.1", DisplayName: "GLM-5.1", InputPerMillion: 1.4, OutputPerMillion: 4.4, CacheRead: 0.26, CacheCreation: 0},
	{ModelID: "glm-5.2", DisplayName: "GLM-5.2", InputPerMillion: 1.4, OutputPerMillion: 4.4, CacheRead: 0.26, CacheCreation: 0},
	{ModelID: "glm-5v-turbo", DisplayName: "GLM-5V-Turbo", InputPerMillion: 1.2, OutputPerMillion: 4, CacheRead: 0.24, CacheCreation: 0},
	{ModelID: "gpt-4.1", DisplayName: "GPT-4.1", InputPerMillion: 2, OutputPerMillion: 8, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "gpt-4.1-mini", DisplayName: "GPT-4.1 Mini", InputPerMillion: 0.4, OutputPerMillion: 1.6, CacheRead: 0.1, CacheCreation: 0},
	{ModelID: "gpt-4.1-nano", DisplayName: "GPT-4.1 Nano", InputPerMillion: 0.1, OutputPerMillion: 0.4, CacheRead: 0.025, CacheCreation: 0},
	{ModelID: "gpt-5", DisplayName: "GPT-5", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-codex", DisplayName: "GPT-5 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-codex-high", DisplayName: "GPT-5 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-codex-low", DisplayName: "GPT-5 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-codex-medium", DisplayName: "GPT-5 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-codex-mini", DisplayName: "GPT-5 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-codex-mini-high", DisplayName: "GPT-5 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-codex-mini-medium", DisplayName: "GPT-5 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-high", DisplayName: "GPT-5", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-low", DisplayName: "GPT-5", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-medium", DisplayName: "GPT-5", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-mini", DisplayName: "GPT-5 Mini", InputPerMillion: 0.25, OutputPerMillion: 2, CacheRead: 0.025, CacheCreation: 0},
	{ModelID: "gpt-5-minimal", DisplayName: "GPT-5", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5-nano", DisplayName: "GPT-5 Nano", InputPerMillion: 0.05, OutputPerMillion: 0.4, CacheRead: 0.005, CacheCreation: 0},
	{ModelID: "gpt-5.1", DisplayName: "GPT-5.1", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-codex", DisplayName: "GPT-5.1 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-codex-max", DisplayName: "GPT-5.1 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-codex-max-high", DisplayName: "GPT-5.1 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-codex-max-xhigh", DisplayName: "GPT-5.1 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-codex-mini", DisplayName: "GPT-5.1 Codex", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-high", DisplayName: "GPT-5.1", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-low", DisplayName: "GPT-5.1", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-medium", DisplayName: "GPT-5.1", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.1-minimal", DisplayName: "GPT-5.1", InputPerMillion: 1.25, OutputPerMillion: 10, CacheRead: 0.125, CacheCreation: 0},
	{ModelID: "gpt-5.2", DisplayName: "GPT-5.2", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-codex", DisplayName: "GPT-5.2 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-codex-high", DisplayName: "GPT-5.2 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-codex-low", DisplayName: "GPT-5.2 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-codex-medium", DisplayName: "GPT-5.2 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-codex-xhigh", DisplayName: "GPT-5.2 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-high", DisplayName: "GPT-5.2", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-low", DisplayName: "GPT-5.2", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-medium", DisplayName: "GPT-5.2", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.2-xhigh", DisplayName: "GPT-5.2", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.3-codex", DisplayName: "GPT-5.3 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.3-codex-high", DisplayName: "GPT-5.3 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.3-codex-low", DisplayName: "GPT-5.3 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.3-codex-medium", DisplayName: "GPT-5.3 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.3-codex-spark", DisplayName: "GPT-5.3 Codex Spark", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.3-codex-xhigh", DisplayName: "GPT-5.3 Codex", InputPerMillion: 1.75, OutputPerMillion: 14, CacheRead: 0.175, CacheCreation: 0},
	{ModelID: "gpt-5.4", DisplayName: "GPT-5.4", InputPerMillion: 2.5, OutputPerMillion: 15, CacheRead: 0.25, CacheCreation: 0},
	{ModelID: "gpt-5.4-mini", DisplayName: "GPT-5.4 Mini", InputPerMillion: 0.75, OutputPerMillion: 4.5, CacheRead: 0.075, CacheCreation: 0},
	{ModelID: "gpt-5.4-nano", DisplayName: "GPT-5.4 Nano", InputPerMillion: 0.2, OutputPerMillion: 1.25, CacheRead: 0.02, CacheCreation: 0},
	{ModelID: "gpt-5.5", DisplayName: "GPT-5.5", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "gpt-5.5-high", DisplayName: "GPT-5.5", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "gpt-5.5-low", DisplayName: "GPT-5.5", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "gpt-5.5-medium", DisplayName: "GPT-5.5", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "gpt-5.5-minimal", DisplayName: "GPT-5.5", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "gpt-5.5-xhigh", DisplayName: "GPT-5.5", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "gpt-5.6", DisplayName: "GPT-5.6 Sol", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "gpt-5.6-high", DisplayName: "GPT-5.6 Sol", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "gpt-5.6-low", DisplayName: "GPT-5.6 Sol", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "gpt-5.6-luna", DisplayName: "GPT-5.6 Luna", InputPerMillion: 0.2, OutputPerMillion: 1.2, CacheRead: 0.02, CacheCreation: 0.25},
	{ModelID: "gpt-5.6-medium", DisplayName: "GPT-5.6 Sol", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "gpt-5.6-minimal", DisplayName: "GPT-5.6 Sol", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "gpt-5.6-sol", DisplayName: "GPT-5.6 Sol", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "gpt-5.6-terra", DisplayName: "GPT-5.6 Terra", InputPerMillion: 2, OutputPerMillion: 12, CacheRead: 0.2, CacheCreation: 2.5},
	{ModelID: "gpt-5.6-xhigh", DisplayName: "GPT-5.6 Sol", InputPerMillion: 5, OutputPerMillion: 30, CacheRead: 0.5, CacheCreation: 6.25},
	{ModelID: "grok-3", DisplayName: "Grok 3", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.75, CacheCreation: 0},
	{ModelID: "grok-3-mini", DisplayName: "Grok 3 Mini", InputPerMillion: 0.25, OutputPerMillion: 0.5, CacheRead: 0.075, CacheCreation: 0},
	{ModelID: "grok-4", DisplayName: "Grok 4", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.75, CacheCreation: 0},
	{ModelID: "grok-4-1-fast-non-reasoning", DisplayName: "Grok 4.1 Fast", InputPerMillion: 0.2, OutputPerMillion: 0.5, CacheRead: 0.05, CacheCreation: 0},
	{ModelID: "grok-4-1-fast-reasoning", DisplayName: "Grok 4.1 Fast Reasoning", InputPerMillion: 0.2, OutputPerMillion: 0.5, CacheRead: 0.05, CacheCreation: 0},
	{ModelID: "grok-4.20-0309-non-reasoning", DisplayName: "Grok 4.20", InputPerMillion: 1.25, OutputPerMillion: 2.5, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "grok-4.20-0309-reasoning", DisplayName: "Grok 4.20 Reasoning", InputPerMillion: 1.25, OutputPerMillion: 2.5, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "grok-4.3", DisplayName: "Grok 4.3", InputPerMillion: 1.25, OutputPerMillion: 2.5, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "grok-4.5", DisplayName: "Grok 4.5", InputPerMillion: 2, OutputPerMillion: 6, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "grok-4.5-build", DisplayName: "Grok 4.5 Build", InputPerMillion: 2, OutputPerMillion: 6, CacheRead: 0.3, CacheCreation: 0},
	{ModelID: "grok-build-0.1", DisplayName: "Grok Build 0.1", InputPerMillion: 1, OutputPerMillion: 2, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "grok-code-fast-1", DisplayName: "Grok Build 0.1 (Code Fast Alias)", InputPerMillion: 1, OutputPerMillion: 2, CacheRead: 0.2, CacheCreation: 0},
	{ModelID: "hunyuan-hy3", DisplayName: "Hunyuan Hy3", InputPerMillion: 0.14, OutputPerMillion: 0.56, CacheRead: 0.035, CacheCreation: 0},
	{ModelID: "hy3", DisplayName: "Hunyuan Hy3", InputPerMillion: 0.14, OutputPerMillion: 0.56, CacheRead: 0.035, CacheCreation: 0},
	{ModelID: "k3", DisplayName: "Kimi K3", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 0},
	{ModelID: "kimi-k2-0905", DisplayName: "Kimi K2", InputPerMillion: 0.55, OutputPerMillion: 2.2, CacheRead: 0.1, CacheCreation: 0},
	{ModelID: "kimi-k2-thinking", DisplayName: "Kimi K2 Thinking", InputPerMillion: 0.55, OutputPerMillion: 2.2, CacheRead: 0.1, CacheCreation: 0},
	{ModelID: "kimi-k2-turbo", DisplayName: "Kimi K2 Turbo", InputPerMillion: 1.11, OutputPerMillion: 8.06, CacheRead: 0.14, CacheCreation: 0},
	{ModelID: "kimi-k2.5", DisplayName: "Kimi K2.5", InputPerMillion: 0.6, OutputPerMillion: 3, CacheRead: 0.1, CacheCreation: 0},
	{ModelID: "kimi-k2.6", DisplayName: "Kimi K2.6", InputPerMillion: 0.95, OutputPerMillion: 4, CacheRead: 0.16, CacheCreation: 0},
	{ModelID: "kimi-k2.7-code", DisplayName: "Kimi K2.7 Code", InputPerMillion: 0.95, OutputPerMillion: 4, CacheRead: 0.19, CacheCreation: 0},
	{ModelID: "kimi-k2.7-code-highspeed", DisplayName: "Kimi K2.7 Code HighSpeed", InputPerMillion: 1.9, OutputPerMillion: 8, CacheRead: 0.38, CacheCreation: 0},
	{ModelID: "kimi-k3", DisplayName: "Kimi K3", InputPerMillion: 3, OutputPerMillion: 15, CacheRead: 0.3, CacheCreation: 0},
	{ModelID: "magistral-medium", DisplayName: "Magistral Medium", InputPerMillion: 2, OutputPerMillion: 5, CacheRead: 0, CacheCreation: 0},
	{ModelID: "magistral-small", DisplayName: "Magistral Small", InputPerMillion: 0.5, OutputPerMillion: 1.5, CacheRead: 0, CacheCreation: 0},
	{ModelID: "mimo-v2-flash", DisplayName: "MiMo V2 Flash", InputPerMillion: 0.09, OutputPerMillion: 0.29, CacheRead: 0.009, CacheCreation: 0},
	{ModelID: "mimo-v2-pro", DisplayName: "MiMo V2 Pro", InputPerMillion: 0.435, OutputPerMillion: 0.87, CacheRead: 0.0036, CacheCreation: 0},
	{ModelID: "mimo-v2.5", DisplayName: "MiMo V2.5", InputPerMillion: 0.14, OutputPerMillion: 0.29, CacheRead: 0.0028, CacheCreation: 0},
	{ModelID: "mimo-v2.5-pro", DisplayName: "MiMo V2.5 Pro", InputPerMillion: 0.435, OutputPerMillion: 0.87, CacheRead: 0.0036, CacheCreation: 0},
	{ModelID: "minimax-m2", DisplayName: "MiniMax M2", InputPerMillion: 0.27, OutputPerMillion: 0.95, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "minimax-m2.1", DisplayName: "MiniMax M2.1", InputPerMillion: 0.27, OutputPerMillion: 0.95, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "minimax-m2.1-lightning", DisplayName: "MiniMax M2.1 Lightning", InputPerMillion: 0.27, OutputPerMillion: 2.33, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "minimax-m2.5", DisplayName: "MiniMax M2.5", InputPerMillion: 0.15, OutputPerMillion: 0.95, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "minimax-m2.5-lightning", DisplayName: "MiniMax M2.5 Lightning", InputPerMillion: 0.3, OutputPerMillion: 2.4, CacheRead: 0.03, CacheCreation: 0},
	{ModelID: "minimax-m2.7", DisplayName: "MiniMax M2.7", InputPerMillion: 0.3, OutputPerMillion: 1.2, CacheRead: 0.06, CacheCreation: 0.375},
	{ModelID: "minimax-m2.7-highspeed", DisplayName: "MiniMax M2.7 Highspeed", InputPerMillion: 0.6, OutputPerMillion: 2.4, CacheRead: 0.06, CacheCreation: 0.375},
	{ModelID: "minimax-m3", DisplayName: "MiniMax M3", InputPerMillion: 0.3, OutputPerMillion: 1.2, CacheRead: 0.06, CacheCreation: 0},
	{ModelID: "mistral-large-3-2512", DisplayName: "Mistral Large 3", InputPerMillion: 0.5, OutputPerMillion: 1.5, CacheRead: 0.05, CacheCreation: 0},
	{ModelID: "mistral-medium-3.1", DisplayName: "Mistral Medium 3.1", InputPerMillion: 0.4, OutputPerMillion: 2, CacheRead: 0.04, CacheCreation: 0},
	{ModelID: "mistral-medium-3.5", DisplayName: "Mistral Medium 3.5", InputPerMillion: 1.5, OutputPerMillion: 7.5, CacheRead: 0, CacheCreation: 0},
	{ModelID: "mistral-small-3.2-24b", DisplayName: "Mistral Small 3.2", InputPerMillion: 0.075, OutputPerMillion: 0.2, CacheRead: 0.01, CacheCreation: 0},
	{ModelID: "mistral-small-4", DisplayName: "Mistral Small 4", InputPerMillion: 0.1, OutputPerMillion: 0.3, CacheRead: 0.01, CacheCreation: 0},
	{ModelID: "o1", DisplayName: "OpenAI o1", InputPerMillion: 15, OutputPerMillion: 60, CacheRead: 7.5, CacheCreation: 0},
	{ModelID: "o1-mini", DisplayName: "OpenAI o1-mini", InputPerMillion: 0.55, OutputPerMillion: 2.2, CacheRead: 0.55, CacheCreation: 0},
	{ModelID: "o3", DisplayName: "OpenAI o3", InputPerMillion: 2, OutputPerMillion: 8, CacheRead: 0.5, CacheCreation: 0},
	{ModelID: "o3-mini", DisplayName: "OpenAI o3-mini", InputPerMillion: 0.55, OutputPerMillion: 2.2, CacheRead: 0.55, CacheCreation: 0},
	{ModelID: "o3-pro", DisplayName: "OpenAI o3-pro", InputPerMillion: 20, OutputPerMillion: 80, CacheRead: 0, CacheCreation: 0},
	{ModelID: "o4-mini", DisplayName: "OpenAI o4-mini", InputPerMillion: 1.1, OutputPerMillion: 4.4, CacheRead: 0.275, CacheCreation: 0},
	{ModelID: "qwen3-235b-a22b", DisplayName: "Qwen3 235B-A22B", InputPerMillion: 0.7, OutputPerMillion: 8.4, CacheRead: 0, CacheCreation: 0},
	{ModelID: "qwen3-32b", DisplayName: "Qwen3 32B", InputPerMillion: 0.16, OutputPerMillion: 0.64, CacheRead: 0, CacheCreation: 0},
	{ModelID: "qwen3-coder-480b", DisplayName: "Qwen3 Coder 480B", InputPerMillion: 0.65, OutputPerMillion: 3.25, CacheRead: 0, CacheCreation: 0},
	{ModelID: "qwen3-coder-480b-a35b-instruct", DisplayName: "Qwen3 Coder 480B-A35B Instruct", InputPerMillion: 0.65, OutputPerMillion: 3.25, CacheRead: 0, CacheCreation: 0},
	{ModelID: "qwen3-coder-flash", DisplayName: "Qwen3 Coder Flash", InputPerMillion: 0.195, OutputPerMillion: 0.975, CacheRead: 0.039, CacheCreation: 0},
	{ModelID: "qwen3-coder-next", DisplayName: "Qwen3 Coder Next", InputPerMillion: 0.12, OutputPerMillion: 0.75, CacheRead: 0, CacheCreation: 0},
	{ModelID: "qwen3-coder-plus", DisplayName: "Qwen3 Coder Plus", InputPerMillion: 0.65, OutputPerMillion: 3.25, CacheRead: 0.13, CacheCreation: 0},
	{ModelID: "qwen3-max", DisplayName: "Qwen3 Max", InputPerMillion: 0.78, OutputPerMillion: 3.9, CacheRead: 0, CacheCreation: 0},
	{ModelID: "qwen3.5-plus", DisplayName: "Qwen3.5 Plus", InputPerMillion: 0.26, OutputPerMillion: 1.56, CacheRead: 0.052, CacheCreation: 0},
	{ModelID: "qwen3.6-flash", DisplayName: "Qwen3.6 Flash", InputPerMillion: 0.1875, OutputPerMillion: 1.125, CacheRead: 0.0375, CacheCreation: 0},
	{ModelID: "qwen3.6-plus", DisplayName: "Qwen3.6 Plus", InputPerMillion: 0.325, OutputPerMillion: 1.95, CacheRead: 0.065, CacheCreation: 0},
	{ModelID: "qwen3.7-max", DisplayName: "Qwen3.7 Max", InputPerMillion: 2.5, OutputPerMillion: 7.5, CacheRead: 0.25, CacheCreation: 0},
	{ModelID: "qwen3.7-plus", DisplayName: "Qwen3.7 Plus", InputPerMillion: 0.4, OutputPerMillion: 1.6, CacheRead: 0.08, CacheCreation: 0},
	{ModelID: "qwq-32b", DisplayName: "QwQ 32B", InputPerMillion: 0.2, OutputPerMillion: 0.6, CacheRead: 0, CacheCreation: 0},
	{ModelID: "qwq-plus", DisplayName: "QwQ Plus", InputPerMillion: 0.8, OutputPerMillion: 2.4, CacheRead: 0, CacheCreation: 0},
	{ModelID: "step-3.5-flash", DisplayName: "Step 3.5 Flash", InputPerMillion: 0.1, OutputPerMillion: 0.3, CacheRead: 0.02, CacheCreation: 0},
	{ModelID: "step-3.5-flash-2603", DisplayName: "Step 3.5 Flash 2603", InputPerMillion: 0.1, OutputPerMillion: 0.3, CacheRead: 0.02, CacheCreation: 0},
	{ModelID: "step-3.7-flash", DisplayName: "Step 3.7 Flash", InputPerMillion: 0.19, OutputPerMillion: 1.13, CacheRead: 0.04, CacheCreation: 0},
}
