// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CredsService 凭据管理服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAgents 返回全部 agent 工具及其当前状态（供 SetupGuide 渲染）
 */
export function GetAgents(): $CancellablePromise<($models.AgentDetail | null)[]> {
    return $Call.ByID(388966094).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetCredStatus 获取三上游凭据状态
 */
export function GetCredStatus(): $CancellablePromise<$models.AllCredStatus | null> {
    return $Call.ByID(620845714).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetLoginURL 获取某上游的登录页 URL
 */
export function GetLoginURL(name: string): $CancellablePromise<string> {
    return $Call.ByID(89820254, name);
}

/**
 * OpenDownloadURL 用系统浏览器打开某上游的下载/官网页
 */
export function OpenDownloadURL(name: string): $CancellablePromise<void> {
    return $Call.ByID(1135465021, name);
}

/**
 * OpenLoginURL 用系统浏览器打开登录页
 */
export function OpenLoginURL(name: string): $CancellablePromise<void> {
    return $Call.ByID(3579937266, name);
}

/**
 * RefreshAllCreds 刷新全部凭据
 */
export function RefreshAllCreds(): $CancellablePromise<void> {
    return $Call.ByID(4022717363);
}

/**
 * RefreshCreds 强制刷新某上游凭据
 */
export function RefreshCreds(name: string): $CancellablePromise<void> {
    return $Call.ByID(714027080, name);
}

/**
 * SetUpstreamEnabled 设置上游启用开关（全局生效；禁用后调用时跳过其下所有模型）
 */
export function SetUpstreamEnabled(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(232698410, name, enabled);
}

// Private type creation functions
const $$createType0 = $models.AgentDetail.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.AllCredStatus.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
