// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService 模型管理服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAutoStrategy 获取 auto 模式策略
 */
export function GetAutoStrategy(): $CancellablePromise<$models.AutoStrategy | null> {
    return $Call.ByID(986115054).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetModels 获取全部可用模型
 */
export function GetModels(): $CancellablePromise<($models.ModelDetail | null)[]> {
    return $Call.ByID(3137098590).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AutoStrategy.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ModelDetail.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
