// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PricingService 费率管理服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Count 费率条数
 */
export function Count(): $CancellablePromise<number> {
    return $Call.ByID(1211064694);
}

/**
 * DeletePrice 删除费率
 */
export function DeletePrice(modelID: string): $CancellablePromise<void> {
    return $Call.ByID(2648232121, modelID);
}

/**
 * ListPrices 列出全部费率
 */
export function ListPrices(): $CancellablePromise<($models.PricingItem | null)[]> {
    return $Call.ByID(3510642361).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetPrice 新增/更新费率
 */
export function SetPrice(item: $models.PricingItem | null): $CancellablePromise<void> {
    return $Call.ByID(2302859194, item);
}

/**
 * SyncFromGitHub 从 GitHub 拉取最新 rates_default.go 并覆盖本地费率
 */
export function SyncFromGitHub(): $CancellablePromise<number> {
    return $Call.ByID(2642077495);
}

// Private type creation functions
const $$createType0 = $models.PricingItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
