// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderAPIService 免费 API 供应商管理服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as providerapi$0 from "../providerapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as upstream$0 from "../upstream/models.js";

/**
 * AddVerifiedModel 评测通过后把模型加入供应商
 */
export function AddVerifiedModel(providerID: string, model: providerapi$0.ProviderModel): $CancellablePromise<void> {
    return $Call.ByID(4116955862, providerID, model);
}

/**
 * BatchBenchmark 以有限并发批量测评多个模型，通过 providerapi:bench 事件推送每个结果。
 * 并发数根据模型数量自动调整：20 个以内用 4，超过 20 用 8。
 */
export function BatchBenchmark(baseURL: string, apiKey: string, prompt: string, protocol: string, maxTokens: number, modelIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(18986741, baseURL, apiKey, prompt, protocol, maxTokens, modelIDs);
}

/**
 * BatchBenchmarkByID 用已保存供应商的密钥批量测评模型。
 */
export function BatchBenchmarkByID(id: string, prompt: string, baseURLOverride: string, protocolOverride: string, maxTokens: number, modelIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1774477321, id, prompt, baseURLOverride, protocolOverride, maxTokens, modelIDs);
}

/**
 * BenchmarkModel 对单个模型直接发请求评测（不经过代理，验证模型可用 + 测 TPS）
 * protocol: "anthropic" 走 /v1/messages + x-api-key；其他走 OpenAI /chat/completions + Bearer。
 * 返回评测结果；通过（success）后由前端决定是否 AddVerifiedModel
 */
export function BenchmarkModel(baseURL: string, apiKey: string, modelID: string, prompt: string, protocol: string, maxTokens: number): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3080884350, baseURL, apiKey, modelID, prompt, protocol, maxTokens).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BenchmarkModelByID 用已保存供应商的密钥测评单个模型。
 */
export function BenchmarkModelByID(id: string, modelID: string, prompt: string, baseURLOverride: string, protocolOverride: string, maxTokens: number): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1010523770, id, modelID, prompt, baseURLOverride, protocolOverride, maxTokens).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearMasterPassword 清除用户主密码，回到自动加密模式（随机密码存钥匙串，启动自动解锁）。
 * 不改动已加密的 apiKey，只重新包裹 DEK；清除后立即重建上游（key 已在内存，调用不受影响）。
 */
export function ClearMasterPassword(): $CancellablePromise<void> {
    return $Call.ByID(1997268660);
}

/**
 * ClearRememberedPassword 清除"记住密码"
 */
export function ClearRememberedPassword(): $CancellablePromise<void> {
    return $Call.ByID(3693837224);
}

/**
 * DecryptShare 用密码解密 .sds，返回供应商列表（导入预览，不写入配置）
 */
export function DecryptShare(dataB64: string, password: string): $CancellablePromise<providerapi$0.ShareProvider[]> {
    return $Call.ByID(2466618774, dataB64, password).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ExportShare 导出选中供应商为加密 .sds 内容（base64）。
 * 文件始终加密（供应商信息也是密文）；includeKey=false 时剥离 API Key。
 */
export function ExportShare(ids: string[], password: string, includeKey: boolean): $CancellablePromise<string> {
    return $Call.ByID(3929967835, ids, password, includeKey);
}

/**
 * FetchProviderModels 测试 base_url + apiKey 能否拉取模型
 * 返回模型 id 列表（能力字段尽量解析）
 */
export function FetchProviderModels(baseURL: string, apiKey: string): $CancellablePromise<upstream$0.FetchedModel[]> {
    return $Call.ByID(2361603833, baseURL, apiKey).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * FetchProviderModelsByID 用已保存供应商的密钥拉取模型列表（明文 key 不经过前端）。
 * baseURLOverride 非空时使用该地址（否则用已存 baseURL）。
 */
export function FetchProviderModelsByID(id: string, baseURLOverride: string): $CancellablePromise<upstream$0.FetchedModel[]> {
    return $Call.ByID(85589749, id, baseURLOverride).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GenerateSharePassword 生成随机分享密码（6 位字母+数字，去易混字符）
 */
export function GenerateSharePassword(): $CancellablePromise<string> {
    return $Call.ByID(1334276033);
}

/**
 * GetBonusProviders 获取注册送 token 的供应商列表（远程优先，回退本地）
 */
export function GetBonusProviders(): $CancellablePromise<providerapi$0.BonusProvider[]> {
    return $Call.ByID(3392143985).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetCatalog 返回免费 API 目录（embed + GitHub + 本地缓存）
 */
export function GetCatalog(): $CancellablePromise<providerapi$0.Catalog | null> {
    return $Call.ByID(1284922869).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetLockStatus 返回锁状态
 */
export function GetLockStatus(): $CancellablePromise<providerapi$0.LocksetInfo> {
    return $Call.ByID(4100075355).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetProviders 返回所有已添加供应商（含模型 verified/healthy 状态）。
 * 安全：通过分享导入的供应商，明文 apiKey 不下发前端（见 SanitizeProviders）。
 */
export function GetProviders(): $CancellablePromise<{ [_ in string]?: providerapi$0.ProviderConfig | null }> {
    return $Call.ByID(1014688056).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetStatus 返回各供应商凭据 + 模型 verified/healthy 状态
 */
export function GetStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(616129984).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportShare 按指令导入供应商（已在前端解决冲突），完成后重建上游
 */
export function ImportShare(items: providerapi$0.ImportItem[]): $CancellablePromise<number> {
    return $Call.ByID(333994982, items);
}

/**
 * InspectShare 读取 .sds 文件头信息（不解密），用于导入前判断是否需要密码、显示版本
 */
export function InspectShare(dataB64: string): $CancellablePromise<providerapi$0.SharePreview | null> {
    return $Call.ByID(2174798797, dataB64).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Lock 锁定 UI（不影响代理调用，不重建上游）
 */
export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(1738986845);
}

/**
 * OpenURL 用系统浏览器打开外部链接（获取 API Key、官网等）
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(850357955, url);
}

/**
 * RecoverWithCode 用恢复码重置主密码，返回新恢复码
 */
export function RecoverWithCode(recoveryCode: string, newPassword: string, remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(2828090959, recoveryCode, newPassword, remember);
}

/**
 * RefreshCatalog 强制从 GitHub 拉最新目录
 */
export function RefreshCatalog(): $CancellablePromise<[providerapi$0.Catalog | null, boolean]> {
    return $Call.ByID(296304964).then(($result: any) => {
        $result[0] = $$createType8($result[0]);
        return $result;
    });
}

/**
 * RemoveModel 从供应商移除某个已加入模型（编辑界面取消加入）
 */
export function RemoveModel(providerID: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(3779821091, providerID, modelID);
}

/**
 * RemoveProvider 删除供应商
 */
export function RemoveProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(4168000787, id);
}

/**
 * ResetForAutoLockout 自动加密锁死时的温和自愈：保留供应商列表，清空 apiKey 重新初始化。
 * 仅在从未设主密码且自动解锁全失败时可用，成功后进入空密钥状态让用户重填 Key。
 */
export function ResetForAutoLockout(): $CancellablePromise<void> {
    return $Call.ByID(3826594660);
}

/**
 * ResetVault 销毁本地加密配置（忘记密码兜底，数据会丢失）
 */
export function ResetVault(): $CancellablePromise<void> {
    return $Call.ByID(3321535887);
}

/**
 * SaveShareFile 弹出原生"另存为"对话框，把加密内容写入用户选择的路径。
 * 返回最终保存的绝对路径；用户取消则返回空字符串。
 */
export function SaveShareFile(dataB64: string): $CancellablePromise<string> {
    return $Call.ByID(1065509296, dataB64);
}

/**
 * SetMasterPassword 设置/更换主密码，返回新恢复码
 */
export function SetMasterPassword(password: string, remember: boolean): $CancellablePromise<string> {
    return $Call.ByID(1032068009, password, remember);
}

/**
 * TryAutoUnlock 尝试用钥匙串记住的密码自动解锁（不暴露密码明文给前端）。
 * 成功返回 true；钥匙串无密码或密码过期返回 false（过期条目会被清除）。
 */
export function TryAutoUnlock(): $CancellablePromise<boolean> {
    return $Call.ByID(1964621628);
}

/**
 * Unlock 用主密码解锁（UI 锁定或启动锁定均适用）
 */
export function Unlock(password: string): $CancellablePromise<void> {
    return $Call.ByID(3848218782, password);
}

/**
 * UpsertProvider 新增/更新供应商配置（保存到 credentials.json + 重建上游）。
 * 编辑已存在的供应商时若 APIKey 为空，保留原 key（前端对导入供应商脱敏，不会回传明文 key）。
 */
export function UpsertProvider(cfg: providerapi$0.ProviderConfig | null): $CancellablePromise<void> {
    return $Call.ByID(2158729804, cfg);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = providerapi$0.ShareProvider.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = upstream$0.FetchedModel.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = providerapi$0.BonusProvider.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = providerapi$0.Catalog.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = providerapi$0.LocksetInfo.createFrom;
const $$createType10 = providerapi$0.ProviderConfig.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = providerapi$0.SharePreview.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
