// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService 代理控制服务（暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxy$0 from "../proxy/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCredStatus 获取三上游凭据状态（合并到代理服务方便前端一次拉取）
 */
export function GetCredStatus(): $CancellablePromise<$models.AllCredStatus | null> {
    return $Call.ByID(3672765669).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDashboard 获取仪表盘聚合数据（状态 + 凭据 + 统计 + 最近日志）
 */
export function GetDashboard(): $CancellablePromise<$models.Dashboard | null> {
    return $Call.ByID(1387702681).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetStatus 获取代理运行状态
 */
export function GetStatus(): $CancellablePromise<proxy$0.ProxyStatus | null> {
    return $Call.ByID(422537337).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RestartProxy 重启代理
 */
export function RestartProxy(): $CancellablePromise<void> {
    return $Call.ByID(2478554900);
}

/**
 * SetPort 修改端口（需重启生效）
 */
export function SetPort(port: number): $CancellablePromise<void> {
    return $Call.ByID(2109416356, port);
}

/**
 * StartProxy 启动代理
 */
export function StartProxy(port: number): $CancellablePromise<void> {
    return $Call.ByID(2043912225, port);
}

/**
 * StopProxy 停止代理
 */
export function StopProxy(): $CancellablePromise<void> {
    return $Call.ByID(977399155);
}

// Private type creation functions
const $$createType0 = $models.AllCredStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Dashboard.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = proxy$0.ProxyStatus.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
