// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CredStatusInfo 凭据状态信息（供 /health 端点和前端展示用）
 */
export class CredStatusInfo {
    "valid": boolean;

    /**
     * ★ 工具是否装了（凭据文件存在）
     */
    "installed": boolean;
    "userId"?: string;
    "expiresAt"?: string;
    "keyPreview"?: string;
    "source": string;
    "lastCheck": string;

    /**
     * ★ 安装/登录引导元数据（从 AgentRegistry 注入）
     * "gui" | "cli"
     */
    "agentType"?: string;

    /**
     * CLI 安装命令
     */
    "installCmd"?: string;

    /**
     * 登录命令
     */
    "loginCmd"?: string;

    /**
     * 官网/下载页
     */
    "downloadUrl"?: string;

    /**
     * 浏览器登录页
     */
    "loginUrl"?: string;

    /** Creates a new CredStatusInfo instance. */
    constructor($$source: Partial<CredStatusInfo> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("lastCheck" in $$source)) {
            this["lastCheck"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredStatusInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CredStatusInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredStatusInfo($$parsedSource as Partial<CredStatusInfo>);
    }
}
